languageCode = 'en-us'
title = 'Spectral by HTML5 UP'
description = 'Another fine responsive site template freebie crafted by HTML5 UP.'
keywords = ''
paginate = 5
theme = 'hugo-spectral'

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# Main Menu
[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Generic Page'
  pageRef = '/generic'
  weight = 20

[[menus.main]]
  name = 'Elements'
  pageRef = '/tags/elements'
  weight = 30

[[menus.main]]
  name = 'Posts'
  pageRef = '/posts'
  weight = 40

# Homepage Configuration
# [params.*] are all optional. Omit to remove section.
# Section keys are required unless commented out
[params]
  # useMarkdown = false
  [params.copyright]
    copyright = 'Untitled'
    copyrightYearStart = '' # only set if different from current year

  # Top Banner
  [params.banner]
    title = 'Spectral'
    description = 'Another fine responsive<br />site template freebie<br />crafted by <a href="http://html5up.net">HTML5 UP</a>.'
    # label = 'Learn More'
    [params.banner.button]
      url = '#'
      label = 'Activate'

  # Sections
  [[params.sections]]
    useMarkdown = false
    sectionLayout = 'wide'
    colorStyle = 'style1'
    title = 'Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep donec'
    description = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
    '''
    [[params.sections.icons]]
      iconName = 'fa-gem'
      # iconStyle = 'regular'
      iconLabel = 'Lorem'
      colorStyle = 'style1'
    [[params.sections.icons]]
      iconName = 'fa-heart'
      # iconStyle = 'regular'
      iconLabel = 'Ipsum'
      colorStyle = 'style2'
    [[params.sections.icons]]
      iconName = 'fa-code'
      iconStyle = 'solid'
      iconLabel = 'Dolor'
      colorStyle = 'style3'

  [[params.sections]]
    sectionLayout = "spotlight"
    [[params.sections.spotlight]]
      title = 'Magna primis lobortis<br />sed ullamcorper'
      description = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'
      image = 'images/pic01.jpg'
    [[params.sections.spotlight]]
      title = 'Tortor dolore feugiat<br />elementum magna'
      description = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'
      image = 'images/pic02.jpg'
    [[params.sections.spotlight]]
      title = 'Augue eleifend aliquet<br />sed condimentum'
      description = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'
      image = 'images/pic03.jpg'

  [[params.sections]]
    sectionLayout = "wide"
    title = 'Accumsan mus tortor nunc aliquet'
    description = 'Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend<br />fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.'
    [[params.sections.features]]
      title = 'Arcu accumsan'
      description = 'Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.'
      iconName = 'fa-paper-plane'
      # iconStyle = 'regular'
    [[params.sections.features]]
      title = 'Ac Augue Eget'
      description = 'Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.'
      iconName = 'fa-laptop'
      iconStyle = 'solid'
    [[params.sections.features]]
      title = 'Mus Scelerisque'
      description = 'Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.'
      iconName = 'fa-code'
      iconStyle = 'solid'
    [[params.sections.features]]
      title = 'Mauris Imperdiet'
      description = 'Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.'
      iconName = 'fa-headphones-alt'
      iconStyle = 'solid'
    [[params.sections.features]]
      title = 'Aenean Primis'
      description = 'Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.'
      iconName = 'fa-heart'
      # iconStyle = 'regular'
    [[params.sections.features]]
      title = 'Tortor Ut'
      description = 'Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat.'
      iconName = 'fa-flag'
      # iconStyle = 'regular'

  # CTA
  [params.cta]
    title = 'Arcue ut vel commodo'
    description = 'Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla.'
    [[params.cta.actions]]
      label = 'Activate'
      url = '#'
      buttonStyle = 'primary'
    [[params.cta.actions]]
      label = 'Learn More'
      url = '#'

  # Social
  [params.social]
  # use fully qualified URL (e.g. https://twitter.com/username)
  twitter_x = ''
  facebook = ''
  instagram = ''
  dribble = ''
  github = ''
  mastodon = ''
  # use email address
  # provide `?subject=my subject` for email contact customization
  email = 'email@example.com'
